:spring_boot_version: current
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot

== Spring Boot Student Service

The Student service provide basic Create, Read, Update and Delete (CRUD) functionality for the management of student records.

NOTE: A Jenkins build is triggered from a commit using serveo exposed webhook.

== Running the Tests

The tests are broken out into unit level tests and service level component tests.
The former uses JUnit exclusively and basically at the level of each working class.
The latter uses Gherkin/Cucumber exclusively and basically at the REST API level.

====

From the command line, the following command will:

- clean the target directory
- compile the service and its tests
- run the unit tests using the maven surefire-plugin with reports generated
- package the service into a jar
- verifies the Gherkin/Cucumber scenarios using the maven failsafe-plugin with reports generated with the service actually started and stop before and after the scenarios are validated. Report results are found in the target directory.

----
mvn clean install
----
====

== Running the Service

To run the application, run the following command in a terminal window (in the `complete`)
directory:

====

Ensure Maven is installed and run the following command in a terminal window (in the `complete`)
directory:

====
[source,text]
----
mvn spring-boot:run
----
====

You should see output similar to the following:

====
[source,text]
----
Loading students:
loading: Student [id=1, firstName=Sam, lastName=Smith, email=sammysmith@live.com, birthDate=2012-03-12]
loading: Student [id=2, firstName=Ralph, lastName=Thomas, email=RalphThomas@gmail.com, birthDate=2010-11-01]
----

====
[source,text]
----
$ curl http://localhost:8080/students
[
{
"id": 1,
"firstName": "Sam",
"lastName": "Smith",
"email": "sammysmith@live.com",
"birthDate": "2012-03-12"
},
{
"id": 2,
"firstName": "Ralph",
"lastName": "Thomas",
"email": "RalphThomas@gmail.com",
"birthDate": "2010-11-01"
}
]

====

The actuator exposes the following:

* http://localhost:8080/actuator/health[actuator/health]
* http://localhost:8080/actuator[actuator]

NOTE: There is also an `/actuator/shutdown` endpoint, but, by default, it is visible only
through JMX. To http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#production-ready-endpoints-enabling-endpoints[enable it as an HTTP endpoint], add
`management.endpoint.shutdown.enabled=true` to your `application.properties` file
and expose it with `management.endpoints.web.exposure.include=health,info,shutdown`.
However, you probably should not enable the shutdown endpoint for a publicly available
application.

You can check the health of the application by running the following command:

====
[source,bash]
----
$ curl http://localhost:8080/actuator/health
{"status":"UP"}
----
====
